version: '3.8'

services:
  game-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/game
    environment:
      - DISPLAY=host.docker.internal:0.0
    network_mode: "host"
    command: tail -f /dev/null

volumes:
  build:
